dynamically wait for newrelic-daemon to be up
instead of two seconds

diff --git a/support/build/extensions/no-debug-non-zts-20121212/newrelic b/support/build/extensions/no-debug-non-zts-20121212/newrelic
--- a/support/build/extensions/no-debug-non-zts-20121212/newrelic
+++ b/support/build/extensions/no-debug-non-zts-20121212/newrelic
@@ -68,11 +68,25 @@ if [[ -n "$NEW_RELIC_LICENSE_KEY" ]]; then
 		# The daemon is a started in foreground mode so it will not daemonize
 		# (i.e. disassociate from the controlling TTY and disappear into the
 		# background).
+		# we use the pidfile to wait for it to be up
+		newrelic_pidfile=/tmp/newrelic-daemon.pid
 
 		# daemon start
-		/app/.heroku/php/bin/newrelic-daemon --foreground --port "@newrelic-daemon" --logfile "/dev/stderr" --loglevel "${NEW_RELIC_DAEMON_LOG_LEVEL}" --pidfile "/tmp/newrelic-daemon.pid" &
-		# give it a moment to connect
-		sleep 2
+		/app/.heroku/php/bin/newrelic-daemon --foreground --port "@newrelic-daemon" --logfile "/dev/stderr" --loglevel "${NEW_RELIC_DAEMON_LOG_LEVEL}" --pidfile "$newrelic_pidfile" &
+		newrelic_pid=$!
+
+		# give it a moment to start up...
+		while ! test -f "$newrelic_pidfile"; do
+			# ...unless it somehow crashes on start, then we have to bail to prevent an infite loop
+			if ! kill -0 $newrelic_pid 2> /dev/null; then # kill -0 checks if process exists
+				echo "Failed to start newrelic-daemon!" >&2
+				break;
+			fi
+			if [[ "$NEW_RELIC_DAEMON_LOG_LEVEL" == "info" || "$NEW_RELIC_DAEMON_LOG_LEVEL" == "debug" ]]; then
+				echo "Waiting for newrelic-daemon..." >&2
+			fi
+			sleep 0.1
+		done
 	else
 		echo >&2 "WARNING: Add-on 'newrelic' detected, but PHP extension not yet installed. Push an update to the application to finish installation of the add-on; an empty change ('git commit --allow-empty') is sufficient."
 	fi
